services:
  app:
    build: .
    environment:
      - TASK_NAME
    networks:
      - isolated
    user: "${DOCKER_USER}"
    volumes:
      - "./:/app:ro"
      - "${KYZYLBORDA_TMPDIR}:/tmp"
      - "../:/task:ro"
networks:
  isolated:
    internal: true
