services:
  app:
    build: ../catbox/app
    environment:
      - TASK_NAME
    networks:
      - isolated
    user: "${DOCKER_USER}"
    volumes:
      - "../catbox/app:/app:ro"
      - "${KYZYLBORDA_TMPDIR}:/tmp"
      - "${STATEDIR}:/state"
      - "./:/task:ro"
networks:
  isolated:
    internal: true
