version: "3.9"
services:
  web:
    build: web
    environment:
      - TASK_NAME
    networks:
      - isolated
    user: "${DOCKER_USER}"
    volumes:
      - "./web:/app:ro"
      - "${KYZYLBORDA_TMPDIR}:/tmp"
      - "${STATEDIR}:/state"
      - "./:/task:ro"
  admin:
    build: admin
    environment:
      - TASK_NAME
      - "SERVICE_HOST=https://${TASK_NAME}.${KYZYLBORDA_DOMAIN}"
    user: "${DOCKER_USER}"
    volumes:
      - "./admin:/app:ro"
      - "${KYZYLBORDA_TMPDIR}:/tmp"
      - "${STATEDIR}:/state"
      - "./:/task:ro"
networks:
  isolated:
    internal: true
