[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
rustix = { version = "0.38.44", features = ["fs"] }
tokio = { version = "1.43.0", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "time"] }
