version: "3.9"
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile.kyzylborda
    environment:
      - TASK_NAME
      - KYZYLBORDA=1
    networks:
      - isolated
    user: "${DOCKER_USER}"
    volumes:
      - "./app:/app:ro"
      - "${KYZYLBORDA_TMPDIR}:/tmp"
      - "${STATEDIR}:/state"
      - "./:/task:ro"
networks:
  isolated:
    internal: true
