services:
  server:
    build:
      dockerfile: Dockerfile.server
    environment:
      - TASK_NAME
    networks:
      - isolated
    user: "${DOCKER_USER}"
    volumes:
      - "${KYZYLBORDA_TMPDIR}:/tmp"
      - "${STATEDIR}:/state"
      - "./:/task:ro"

networks:
  isolated:
    internal: true
