category: reverse
points: 400
title:
  ru: Просеиватель
  en: Sifter
author: sylfn
description:
  ru: |
    <p>
      В УНИИИУ разработали супер-компьютер. (Время, правда, в УНИИИУ идёт чуть иначе, чем у нас, так
      что у вас может сложиться иное впечатление.) Мы получили доступ к его прототипу. Раскройте
      секреты уцуцуги вместе с нами!
    </p>
  en: |
    <p>
      URIRU has developed a supercomputer. (Time, however, passes differently in URIRU, so your
      mileage may vary.) We got our hands on its prototype. Let's decipher the secrets of ucucuga
      together!
    </p>
generator: ../_scripts/kyzylborda-lib-generator
daemon:
  exec: kyzylborda-docker-compose-daemon
  cwd: .
  socket: ./external.sock
  socket_type: http
secrets:
  seed: f6Z+6fIvkFkwH8aFxQ0Xg41BPh6KVBEq
  flag: ugra_commodore_64_basic_v2_amiga_rulez_[a-z0-9]{8}
